# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 12:03
from __future__ import unicode_literals

import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='\u041c\u0430\u0448\u0438\u043d\u043d\u043e\u0435 \u0438\u043c\u044f')),
                ('title', models.CharField(max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=articles.models._upload_to, verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430')),
                ('html', models.TextField(blank=True, verbose_name='HTML')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '\u0427\u0435\u0440\u043d\u043e\u0432\u0438\u043a'), (2, '\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e'), (3, '\u0423\u0434\u0430\u043b\u0435\u043d\u043e')], default=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u044f')),
                ('multi_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='accounts.MultiAccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043d\u0442\u0435\u043d\u0442',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0435\u043d\u0442',
            },
        ),
        migrations.CreateModel(
            name='ArticleContentPhotoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=articles.models._upload_to, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['content_item', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ArticleColumn',
            fields=[
                ('articlecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.ArticleContent')),
                ('image', models.ImageField(upload_to=articles.models._upload_to, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 [MARKDOWN]')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043b\u043e\u043d\u043a\u0430',
                'verbose_name_plural': '\u041a\u043e\u043b\u043e\u043d\u043a\u0438',
            },
            bases=('articles.articlecontent',),
        ),
        migrations.CreateModel(
            name='ArticleContenLead',
            fields=[
                ('articlecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.ArticleContent')),
                ('text', models.TextField(max_length=400, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
            ],
            options={
                'abstract': False,
            },
            bases=('articles.articlecontent',),
        ),
        migrations.CreateModel(
            name='ArticleContentEmbed',
            fields=[
                ('articlecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.ArticleContent')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '\u041f\u043e\u0441\u0442'), (2, '\u0412\u0438\u0434\u0435\u043e'), (3, '\u0410\u0443\u0434\u0438\u043e')], default=1, verbose_name='\u0422\u0438\u043f')),
                ('url', models.URLField(max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
            ],
            options={
                'verbose_name': 'Embed',
            },
            bases=('articles.articlecontent',),
        ),
        migrations.CreateModel(
            name='ArticleContentHeader',
            fields=[
                ('articlecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.ArticleContent')),
                ('text', models.CharField(max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
            ],
            options={
                'abstract': False,
            },
            bases=('articles.articlecontent',),
        ),
        migrations.CreateModel(
            name='ArticleContentImageCollection',
            fields=[
                ('articlecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.ArticleContent')),
            ],
            options={
                'abstract': False,
            },
            bases=('articles.articlecontent',),
        ),
        migrations.CreateModel(
            name='ArticleContentText',
            fields=[
                ('articlecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.ArticleContent')),
                ('text', models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 [MARKDOWN]')),
            ],
            options={
                'abstract': False,
            },
            bases=('articles.articlecontent',),
        ),
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('articlecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.ArticleContent')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '\u041d\u0435\u043f\u0440\u043e\u043d\u0443\u043c\u0435\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439'), (2, '\u041f\u0440\u043e\u043d\u0443\u043c\u0435\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439')], default=1, verbose_name='\u0422\u0438\u043f')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 [MARKDOWN]')),
            ],
            options={
                'verbose_name': '\u0421\u043f\u0438\u0441\u043e\u043a',
                'verbose_name_plural': '\u0421\u043f\u0438\u0441\u043a\u0438',
            },
            bases=('articles.articlecontent',),
        ),
        migrations.CreateModel(
            name='ArticlePhrase',
            fields=[
                ('articlecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.ArticleContent')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 [MARKDOWN]')),
            ],
            options={
                'verbose_name': '\u0424\u0440\u0430\u0437\u0430',
                'verbose_name_plural': '\u0424\u0440\u0430\u0437\u044b',
            },
            bases=('articles.articlecontent',),
        ),
        migrations.CreateModel(
            name='ArticleQuote',
            fields=[
                ('articlecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.ArticleContent')),
                ('photo', models.ImageField(upload_to=articles.models._upload_to, verbose_name='\u0424\u043e\u0442\u043e')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u0426\u0438\u0442\u0430\u0442\u0430',
                'verbose_name_plural': '\u0426\u0438\u0442\u0430\u0442\u044b',
            },
            bases=('articles.articlecontent',),
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_articles.articlecontent_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='articlecontentphotoitem',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='articles.ArticleContentImageCollection'),
        ),
    ]
