# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20161227_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecontent',
            options={'ordering': ['article', 'position'], 'verbose_name': '\u041a\u043e\u043d\u0442\u0435\u043d\u0442', 'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0435\u043d\u0442'},
        ),
        migrations.AlterField(
            model_name='articlecontentheader',
            name='text',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='articlecontentlead',
            name='text',
            field=models.TextField(blank=True, max_length=400, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
