# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170105_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContentPhrase',
            fields=[
                ('articlecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.ArticleContent')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'abstract': False,
            },
            bases=('articles.articlecontent',),
        ),
        migrations.AlterField(
            model_name='articlecontentheader',
            name='text',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='articlecontentlead',
            name='text',
            field=models.TextField(blank=True, max_length=400, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
