# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20170107_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecontentembed',
            old_name='type',
            new_name='subtype',
        ),
        migrations.RenameField(
            model_name='articlecontentlist',
            old_name='type',
            new_name='subtype',
        ),
    ]
