# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20170107_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontentlist',
            name='text',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 [MARKDOWN]'),
        ),
    ]
