# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20170108_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleContentImage',
            new_name='ArticleContentPhoto',
        ),
    ]
