# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20170108_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContentPhotoGallery',
            fields=[
                ('articlecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.ArticleContent')),
                ('subtype', models.PositiveSmallIntegerField(choices=[(1, '\u0422\u0438\u043f 1')], default=1, verbose_name='\u0422\u0438\u043f')),
            ],
            options={
                'abstract': False,
            },
            bases=('articles.articlecontent',),
        ),
    ]
