# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_articlecontentphotogallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontentphoto',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='articles.ArticleContentPhotoGallery'),
        ),
    ]
