# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20170108_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecontentimagecollection',
            name='articlecontent_ptr',
        ),
        migrations.DeleteModel(
            name='ArticleContentImageCollection',
        ),
    ]
