# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 06:53
from __future__ import unicode_literals

import articles.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20170108_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=articles.models._upload_to, verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
            ],
        ),
        migrations.RemoveField(
            model_name='articlecontent',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlecontent',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='articlecontentcolumn',
            name='articlecontent_ptr',
        ),
        migrations.RemoveField(
            model_name='articlecontentembed',
            name='articlecontent_ptr',
        ),
        migrations.RemoveField(
            model_name='articlecontentheader',
            name='articlecontent_ptr',
        ),
        migrations.RemoveField(
            model_name='articlecontentlead',
            name='articlecontent_ptr',
        ),
        migrations.RemoveField(
            model_name='articlecontentlist',
            name='articlecontent_ptr',
        ),
        migrations.RemoveField(
            model_name='articlecontentphoto',
            name='content_item',
        ),
        migrations.RemoveField(
            model_name='articlecontentphotogallery',
            name='articlecontent_ptr',
        ),
        migrations.RemoveField(
            model_name='articlecontentphrase',
            name='articlecontent_ptr',
        ),
        migrations.RemoveField(
            model_name='articlecontentquote',
            name='articlecontent_ptr',
        ),
        migrations.RemoveField(
            model_name='articlecontenttext',
            name='articlecontent_ptr',
        ),
        migrations.RemoveField(
            model_name='article',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='article',
            name='multi_account',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'blocks': [], 'cover': None, 'title': None}, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
        migrations.DeleteModel(
            name='ArticleContent',
        ),
        migrations.DeleteModel(
            name='ArticleContentColumn',
        ),
        migrations.DeleteModel(
            name='ArticleContentEmbed',
        ),
        migrations.DeleteModel(
            name='ArticleContentHeader',
        ),
        migrations.DeleteModel(
            name='ArticleContentLead',
        ),
        migrations.DeleteModel(
            name='ArticleContentList',
        ),
        migrations.DeleteModel(
            name='ArticleContentPhoto',
        ),
        migrations.DeleteModel(
            name='ArticleContentPhotoGallery',
        ),
        migrations.DeleteModel(
            name='ArticleContentPhrase',
        ),
        migrations.DeleteModel(
            name='ArticleContentQuote',
        ),
        migrations.DeleteModel(
            name='ArticleContentText',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.Article', verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f'),
        ),
    ]
