# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20170111_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ads_enabled',
            field=models.BooleanField(default=True, verbose_name='\u0420\u0435\u043a\u043b\u0430\u043c\u0430 \u0432\u043a\u043b\u044e\u0447\u0435\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='article',
            name='link_access',
            field=models.BooleanField(default=False, verbose_name='\u0414\u043e\u0441\u0442\u0443\u043f \u043f\u043e \u0441\u0441\u044b\u043b\u043a\u0435'),
        ),
    ]
