# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 09:03
from __future__ import unicode_literals

import articles.models
import articles.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20170116_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={b'blocks': [], b'cover': None, b'title': ''}, validators=[articles.validators.validate_content_size, articles.models.validate_content], verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442'),
        ),
    ]
