# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20170202_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True, verbose_name='\u041c\u0430\u0448\u0438\u043d\u043d\u043e\u0435 \u0438\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '\u0427\u0435\u0440\u043d\u043e\u0432\u0438\u043a'), (2, '\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e'), (3, '\u0423\u0434\u0430\u043b\u0435\u043d\u043e'), (4, '\u041e\u0431\u0449\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e')], default=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
    ]
