# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20170215_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleview',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'),
        ),
    ]
