# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_articleview_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UID')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u0430\u044f')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u0430')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='articles.Article', verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0435\u0432\u044c\u044e',
                'verbose_name_plural': '\u041f\u0440\u0435\u0432\u044c\u044e',
            },
        ),
    ]
