# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20170425_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleview',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='articleview',
            name='views_count',
        ),
        migrations.AddField(
            model_name='articleview',
            name='monetization_enabled',
            field=models.BooleanField(default=False, verbose_name='\u041c\u043e\u043d\u0435\u0442\u0438\u0437\u0438\u0440\u0443\u0435\u043c\u044b\u0439 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440'),
        ),
    ]
