# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_auto_20170502_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='paywall_currency',
            field=models.CharField(choices=[(b'Ruble', b'RUR'), (b'US Dollar', b'USD'), (b'Euro', b'EUR')], default=b'RUR', max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430 [PAYWALL]'),
        ),
        migrations.AddField(
            model_name='article',
            name='paywall_enabled',
            field=models.BooleanField(default=False, verbose_name='Paywall \u0432\u043a\u043b\u044e\u0447\u0435\u043d'),
        ),
        migrations.AddField(
            model_name='article',
            name='paywall_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u0411\u0430\u0437\u043e\u0432\u0430\u044f \u0441\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0434\u043e\u0441\u0442\u0443\u043f\u0430 [PAYWALL]'),
        ),
    ]
