# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_auto_20170503_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='paywall_currency',
            field=models.CharField(choices=[(b'RUR', b'Ruble'), (b'USD', b'US Dollar'), (b'EUR', b'Euro')], default=b'RUR', max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430 [PAYWALL]'),
        ),
    ]
