# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-22 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_auto_20170504_1302'),
        ('articles', '0027_article_title'),
    ]

    operations = [
    ]
