# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_auto_20170523_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleuseraccess',
            options={'verbose_name': '\u0414\u043e\u0441\u0442\u0443\u043f \u043a \u0441\u0442\u0430\u0442\u044c\u0435', 'verbose_name_plural': '\u0414\u043e\u0441\u0442\u0443\u043f\u044b \u043a \u0441\u0442\u0430\u0442\u044c\u044f\u043c'},
        ),
        migrations.RemoveField(
            model_name='articleuseraccess',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='articleuseraccess',
            name='uid',
        ),
    ]
