# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('articles', '0031_auto_20170616_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleuseraccess',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='payments.PayWallOrder', verbose_name='\u0417\u0430\u043a\u0430\u0437'),
        ),
        migrations.AlterField(
            model_name='articleuseraccess',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='articles.Article', verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f'),
        ),
    ]
