# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_auto_20170704_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='\u0417\u0430\u043a\u0440\u0435\u043f\u043b\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '\u0427\u0435\u0440\u043d\u043e\u0432\u0438\u043a'), (2, '\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e'), (3, '\u0423\u0434\u0430\u043b\u0435\u043d\u043e'), (4, '\u041e\u0431\u0449\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e'), (5, '\u0417\u0430\u0431\u043b\u043e\u043a\u0438\u0440\u043e\u0432\u0430\u043d\u043e')], db_index=True, default=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
    ]
