# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 13:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payment
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0028_auto_20170504_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '\u0410\u043a\u0442\u0438\u0432\u043d\u043e'), (2, '\u0417\u0430\u0431\u043b\u043e\u043a\u0438\u0440\u043e\u0432\u0430\u043d\u043e')], default=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('currency', models.CharField(choices=[(b'RUR', b'Ruble'), (b'USD', b'US Dollar'), (b'EUR', b'Euro')], default=b'RUR', max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u0411\u0430\u043b\u0430\u043d\u0441')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u0448\u0435\u043b\u0435\u043a',
                'verbose_name_plural': '\u041a\u043e\u0448\u0435\u043b\u044c\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='PaywallOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=payment.generate_paywall_order_number, max_length=8, unique=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u0412 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435'), (1, '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d'), (2, '\u041e\u0442\u043c\u0435\u043d\u0435\u043d')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('price_cached', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u0426\u0435\u043d\u0430')),
                ('currency', models.CharField(choices=[(b'RUR', b'Ruble'), (b'USD', b'US Dollar'), (b'EUR', b'Euro')], default=b'RUR', editable=False, max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paywall_orders', to='articles.Article', verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043b\u0430\u0442\u0435\u043b\u044c\u0449\u0438\u043a')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437 Paywall',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b Paywall',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('advertisement', '\u0420\u0435\u043a\u043b\u0430\u043c\u0430'), ('paywall', 'Paywall'), ('withdrawal', '\u0412\u044b\u0432\u043e\u0434')], max_length=20, verbose_name='\u0422\u0438\u043f')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0421\u0443\u043c\u043c\u0430')),
                ('currency', models.CharField(choices=[(b'RUR', b'Ruble'), (b'USD', b'US Dollar'), (b'EUR', b'Euro')], default=b'RUR', editable=False, max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.Transaction')),
            ],
            bases=('payment.transaction',),
        ),
        migrations.CreateModel(
            name='PaywallTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.Transaction')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaywallOrder', verbose_name='\u0417\u0430\u043a\u0430\u0437')),
            ],
            bases=('payment.transaction',),
        ),
        migrations.CreateModel(
            name='WithdrawalTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.Transaction')),
            ],
            bases=('payment.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.PaymentAccount', verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentaccount',
            unique_together=set([('user', 'currency')]),
        ),
    ]
