# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-26 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e')),
                ('code', models.TextField(verbose_name='\u041a\u043e\u0434')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u0434 \u0441\u0447\u0435\u0442\u0447\u0438\u043a\u0430',
                'verbose_name_plural': '\u041a\u043e\u0434 \u0441\u0447\u0435\u0442\u0447\u0438\u043a\u043e\u0432',
            },
        ),
    ]
