# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170109_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043b\u0441\u044f')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0434\u043f\u0438\u0441\u043a\u0430',
                'verbose_name_plural': '\u041f\u043e\u0434\u043f\u0438\u0441\u043a\u0438',
            },
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': '\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0439 \u0430\u043a\u043a\u0430\u0443\u043d\u0442', 'verbose_name_plural': '\u0421\u0441\u044b\u043b\u043a\u0438 \u043d\u0430 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u044b'},
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_subscribers_cached',
            field=models.IntegerField(default=0, editable=False, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='social',
            field=models.CharField(choices=[('vk', '\u0412 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0435'), ('fb', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('google', 'Google'), ('OK', '\u041e\u0434\u043d\u043e\u043a\u043b\u0430\u0441\u0441\u043d\u0438\u043a\u0438'), ('Youtube', 'Youtube')], max_length=20, verbose_name='\u0421\u043e\u0446\u0441\u0435\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('user', 'author')]),
        ),
    ]
