# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170110_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='\u0410\u043a\u043a\u0430\u0443\u043d\u0442 \u0430\u0432\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='\u0421\u043a\u0440\u044b\u0442\u0430'),
        ),
    ]
