# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170112_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ('id',), 'verbose_name': '\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0439 \u0430\u043a\u043a\u0430\u0443\u043d\u0442', 'verbose_name_plural': '\u0421\u0441\u044b\u043b\u043a\u0438 \u043d\u0430 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u044b'},
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='social',
            field=models.CharField(choices=[('vk', '\u0412 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0435'), ('fb', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('google', 'Google'), ('OK', '\u041e\u0434\u043d\u043e\u043a\u043b\u0430\u0441\u0441\u043d\u0438\u043a\u0438'), ('Youtube', 'Youtube'), ('Web', 'Web')], default='Web', max_length=20, verbose_name='\u0421\u043e\u0446\u0441\u0435\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(max_length=255, verbose_name='URL'),
        ),
    ]
