# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_phonecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonecode',
            name='user',
        ),
        migrations.AddField(
            model_name='phonecode',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0442\u043a\u043b\u044e\u0447\u0435\u043d'),
        ),
        migrations.AddField(
            model_name='phonecode',
            name='hash',
            field=models.CharField(blank='', default='', editable=False, max_length=50, verbose_name='\u0425\u044d\u0448'),
        ),
        migrations.AddField(
            model_name='phonecode',
            name='phone',
            field=models.CharField(default='1', max_length=20, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
