# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170117_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecode',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
