# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170202_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_published_articles_cached',
            field=models.IntegerField(default=0, editable=False, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u0441\u0442\u0430\u0442\u0435\u0439'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
