# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_subscriptions_cached',
            field=models.IntegerField(default=0, editable=False, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043f\u043e\u0434\u043f\u0438c\u043e\u043a'),
        ),
    ]
