# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_number_of_subscriptions_cached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='social',
            field=models.CharField(choices=[('vk', '\u0412 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0435'), ('fb', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('google', 'Google'), ('OK', '\u041e\u0434\u043d\u043e\u043a\u043b\u0430\u0441\u0441\u043d\u0438\u043a\u0438'), ('Youtube', 'Youtube'), ('web', 'Web')], default='web', max_length=20, verbose_name='\u0421\u043e\u0446\u0441\u0435\u0442\u044c'),
        ),
    ]
