# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20170425_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='\u041d\u0438\u043a\u043d\u0435\u0439\u043c'),
        ),
    ]
