# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20170320_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='\u0412\u0435\u0441 \u043f\u043e\u043a\u0430\u0437\u0430 \u0431\u0430\u043d\u043d\u0435\u0440\u0430 \u0432 \u0440\u044f\u0434\u0443 \u0431\u0430\u043d\u043d\u0435\u0440\u043e\u0432 \u0441 \u0430\u043d\u0430\u043b\u043e\u0433\u0438\u0447\u043d\u044b\u043c \u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u043e\u043c', verbose_name='\u0412\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='identifier',
            field=models.CharField(choices=[(b'BANNER_RIGHT_SIDE', b'banner__right_side'), (b'__module__', b'advertisement'), (b'BANNER_CONTENT_MOBILE', b'banner__content__mobile'), (b'BANNER_CONTENT_INLINE_MOBILE', b'banner__content_inline__mobile'), (b'BANNER_TOP_MOBILE', b'banner__top__mobile'), (b'BANNER_CONTENT', b'banner__content'), (b'BANNER_TOP', b'banner__top'), (b'BANNER_CONTENT_INLINE', b'banner__content_inline'), (b'__doc__', None)], max_length=255, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440'),
        ),
    ]
