# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_auto_20170425_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_mobile',
            field=models.BooleanField(default=False, verbose_name='\u041c\u043e\u0431\u0438\u043b\u044c\u043d\u0430\u044f \u0432\u0435\u0440\u0441\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='identifier',
            field=models.CharField(choices=[(b'banner__right_side', b'banner__right_side'), (b'banner__content__mobile', b'banner__content__mobile'), (b'banner__content_inline__mobile', b'banner__content_inline__mobile'), (b'banner__top__mobile', b'banner__top__mobile'), (b'banner__content', b'banner__content'), (b'banner__top', b'banner__top'), (b'banner__content_inline', b'banner__content_inline')], max_length=255, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440'),
        ),
    ]
