# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_auto_20170427_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(choices=[(b'banner__right_side', b'banner__right_side'), (b'banner__content', b'banner__content'), (b'banner__top', b'banner__top'), (b'banner__content_inline', b'banner__content_inline')], max_length=255, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u0437\u0438\u0446\u0438\u0438')),
                ('is_mobile', models.BooleanField(default=False, help_text='\u0411\u0430\u043d\u043d\u0435\u0440 \u0434\u043b\u044f \u043c\u043e\u0431\u0438\u043b\u044c\u043d\u043e\u0439 \u0432\u0435\u0440\u0441\u0438\u0438 \u0441\u0430\u0439\u0442\u0430', verbose_name='\u041c\u043e\u0431\u0438\u043b\u044c\u043d\u0430\u044f \u0432\u0435\u0440\u0441\u0438\u044f')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
            ],
            options={
                'ordering': ['identifier'],
                'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430 \u0431\u0430\u043d\u043d\u0435\u0440\u043e\u0432',
                'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b \u0431\u0430\u043d\u043d\u0435\u0440\u043e\u0432',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-weight'], 'verbose_name': '\u0411\u0430\u043d\u043d\u0435\u0440', 'verbose_name_plural': '\u0411\u0430\u043d\u043d\u0435\u0440\u044b'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='is_mobile',
        ),
        migrations.AddField(
            model_name='banner',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u0412\u044b\u0441\u043e\u0442\u0430, px'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_ab',
            field=models.BooleanField(default=False, verbose_name='\u0423\u0447\u0430\u0441\u0442\u0432\u0443\u0435\u0442 \u0432 A/B \u0442\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_fullwidth',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0430 \u0432\u0441\u044e \u0448\u0438\u0440\u0438\u043d\u0443'),
        ),
        migrations.AddField(
            model_name='banner',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='banner',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u0428\u0438\u0440\u0438\u043d\u0430, px'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='\u0412\u0435\u0441 \u043f\u043e\u043a\u0430\u0437\u0430 \u0431\u0430\u043d\u043d\u0435\u0440\u0430 \u0434\u043b\u044f A/B \u0442\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f \u0432 \u0433\u0440\u0443\u043f\u043f\u0435', verbose_name='\u0412\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='banner',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='advertisement.BannerGroup', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430'),
        ),
    ]
