# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_auto_20170510_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='code',
            field=models.TextField(unique=True, verbose_name='\u041a\u043e\u0434 \u0431\u0430\u043d\u043d\u0435\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='bannergroup',
            name='identifier',
            field=models.CharField(choices=[(b'banner__right_side', b'banner__right_side'), (b'banner__content', b'banner__content'), (b'banner__top', b'banner__top'), (b'banner__content_inline', b'banner__content_inline'), (b'banner__bottom', b'banner__bottom')], max_length=255, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u0437\u0438\u0446\u0438\u0438'),
        ),
        migrations.AlterUniqueTogether(
            name='bannergroup',
            unique_together=set([('identifier', 'is_mobile')]),
        ),
    ]
