# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_auto_20170510_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='code',
            field=models.TextField(verbose_name='\u041a\u043e\u0434 \u0431\u0430\u043d\u043d\u0435\u0440\u0430'),
        ),
    ]
