# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-09 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_auto_20170718_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['position'], 'verbose_name': '\u0411\u0430\u043d\u043d\u0435\u0440', 'verbose_name_plural': '\u0411\u0430\u043d\u043d\u0435\u0440\u044b'},
        ),
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f'),
        ),
    ]
