# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-07 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_auto_20170809_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='\u0412\u0435\u0441'),
        ),
    ]
