# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0027_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAggregatedStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430 \u043f\u043e\u0434\u0441\u0447\u0435\u0442\u0430')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u043f\u043e\u0434\u0441\u0447\u0435\u0442\u0430')),
                ('views', models.PositiveIntegerField(blank=True, help_text='\u041e\u0431\u0449\u0435\u0435 \u043a\u043e\u043b-\u0432\u043e \u0443\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0445 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432', null=True, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b')),
                ('views_yandex', models.PositiveIntegerField(blank=True, help_text='\u041e\u0431\u0449\u0435\u0435 \u043a\u043e\u043b-\u0432\u043e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432 \u0438\u0437 Yandex.Metrics', null=True, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b [Yandex]')),
                ('male_percent', models.FloatField(blank=True, null=True, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u043c\u0443\u0436\u0447\u0438\u043d')),
                ('age_interval_17', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u043b\u044e\u0434\u0435\u0439 \u0432 \u0432\u043e\u0437\u0440\u0430\u0441\u0442\u0435 \u0434\u043e 18 \u043b\u0435\u0442')),
                ('age_interval_18', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u043b\u044e\u0434\u0435\u0439 \u0432 \u0432\u043e\u0437\u0440\u0430\u0441\u0442\u0435 \u043e\u0442 18 \u0434\u043e 24 \u043b\u0435\u0442')),
                ('age_interval_25', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u043b\u044e\u0434\u0435\u0439 \u0432 \u0432\u043e\u0437\u0440\u0430\u0441\u0442\u0435 \u043e\u0442 25 \u0434\u043e 34 \u043b\u0435\u0442')),
                ('age_interval_35', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u043b\u044e\u0434\u0435\u0439 \u0432 \u0432\u043e\u0437\u0440\u0430\u0441\u0442\u0435 \u043e\u0442 35 \u0434\u043e 44 \u043b\u0435\u0442')),
                ('age_interval_45', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u043b\u044e\u0434\u0435\u0439 \u0432 \u0432\u043e\u0437\u0440\u0430\u0441\u0442\u0435 \u043e\u0442 45 \u043b\u0435\u0442')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='articles.Article', verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f')),
            ],
            options={
                'verbose_name': '\u041e\u0431\u0449\u0430\u044f \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u0441\u0442\u0430\u0442\u044c\u0438',
                'verbose_name_plural': '\u041e\u0431\u0449\u0438\u0435 \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0438 \u0441\u0442\u0430\u0442\u044c\u0438',
            },
        ),
    ]
