# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleaggregatedstatistics',
            old_name='age_interval_17',
            new_name='age_17',
        ),
        migrations.RenameField(
            model_name='articleaggregatedstatistics',
            old_name='age_interval_18',
            new_name='age_18',
        ),
        migrations.RenameField(
            model_name='articleaggregatedstatistics',
            old_name='age_interval_25',
            new_name='age_25',
        ),
        migrations.RenameField(
            model_name='articleaggregatedstatistics',
            old_name='age_interval_35',
            new_name='age_35',
        ),
        migrations.RenameField(
            model_name='articleaggregatedstatistics',
            old_name='age_interval_45',
            new_name='age_45',
        ),
    ]
