# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statistics', '0003_articleviewsstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorViewsStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '\u0414\u043d\u0435\u0432\u043d\u043e\u0439 \u043f\u0435\u0440\u0438\u043e\u0434'), (2, '\u041c\u0435\u0441\u044f\u0447\u043d\u044b\u0439 \u043f\u0435\u0440\u0438\u043e\u0434')], verbose_name='\u0422\u0438\u043f')),
                ('views_count', models.PositiveIntegerField(verbose_name='\u041a\u043e\u043b-\u0432\u043e \u0443\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0445 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432')),
                ('date_start', models.DateTimeField(verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u043f\u0435\u0440\u0438\u043e\u0434\u0430 \u043e\u0442\u0447\u0435\u0442\u0430')),
                ('date_end', models.DateTimeField(verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u043f\u0435\u0440\u0438\u043e\u0434\u0430 \u043e\u0442\u0447\u0435\u0442\u0430')),
                ('interval_start', models.DateTimeField(verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0438\u043d\u0442\u0435\u0440\u0432\u0430\u043b\u0430 \u0432\u0440\u0435\u043c\u0435\u043d\u0438')),
                ('interval_end', models.DateTimeField(verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u0438\u043d\u0442\u0435\u0440\u0432\u0430\u043b\u0430 \u0432\u0440\u0435\u043c\u0435\u043d\u0438')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_statistics', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440')),
            ],
            options={
                'ordering': ['date_end', 'interval_end'],
                'abstract': False,
                'verbose_name': '\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b \u0430\u0432\u0442\u043e\u0440\u0430',
                'verbose_name_plural': '\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b \u0430\u0432\u0442\u043e\u0440\u043e\u0432',
            },
        ),
        migrations.AlterModelOptions(
            name='articleviewsstatistics',
            options={'ordering': ['date_end', 'interval_end'], 'verbose_name': '\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b \u0441\u0442\u0430\u0442\u044c\u0438', 'verbose_name_plural': '\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b \u0441\u0442\u0430\u0442\u0435\u0439'},
        ),
        migrations.AlterField(
            model_name='articleviewsstatistics',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_statistics', to='articles.Article', verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f'),
        ),
    ]
