# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0007_auto_20170519_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorviewsstatistics',
            name='author',
        ),
        migrations.DeleteModel(
            name='AuthorViewsStatistics',
        ),
    ]
