# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlshort',
            options={'verbose_name': '\u0421\u043e\u043a\u0440\u0430\u0449\u0435\u043d\u043d\u0430\u044f \u0441\u0441\u044b\u043b\u043a\u0430', 'verbose_name_plural': '\u0421\u043e\u043a\u0440\u0430\u0449\u0435\u043d\u044b\u0435 \u0441\u0441\u044b\u043b\u043a\u0438'},
        ),
        migrations.AlterField(
            model_name='urlshort',
            name='code',
            field=models.CharField(default='', editable=False, max_length=10, unique=True, verbose_name='\u041a\u043e\u0434'),
        ),
    ]
