# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_auto_20170425_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='url',
            field=models.URLField(db_index=True, verbose_name='URL'),
        ),
    ]
