# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20170425_1106'),
        ('url_shortener', '0003_auto_20170425_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshort',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_url', to='articles.Article', verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f'),
        ),
        migrations.AlterField(
            model_name='urlshort',
            name='url',
            field=models.URLField(blank=True, db_index=True, verbose_name='URL'),
        ),
    ]
