# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0004_auto_20170426_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='url',
            field=models.TextField(blank=True, db_index=True, max_length=1000, verbose_name='URL'),
        ),
    ]
